New-Item -ItemType Directory -Force -Path "C:\Users\ozan_\L'art_Peyzaj\l-art-peyzaj-web\public\projects"
$brain = "C:\Users\ozan_\.gemini\antigravity\brain\b0a28518-5479-440c-911b-140fae577f97"
Copy-Item "$brain\project_villa_garden_1773604486169.png" "C:\Users\ozan_\L'art_Peyzaj\l-art-peyzaj-web\public\projects\villa-garden.png"
Copy-Item "$brain\project_urban_park_1773604501247.png" "C:\Users\ozan_\L'art_Peyzaj\l-art-peyzaj-web\public\projects\urban-park.png"
Copy-Item "$brain\project_rooftop_garden_1773604515579.png" "C:\Users\ozan_\L'art_Peyzaj\l-art-peyzaj-web\public\projects\rooftop-garden.png"
Copy-Item "$brain\project_zen_garden_1773604529991.png" "C:\Users\ozan_\L'art_Peyzaj\l-art-peyzaj-web\public\projects\zen-garden.png"
Copy-Item "$brain\project_lake_house_1773604545574.png" "C:\Users\ozan_\L'art_Peyzaj\l-art-peyzaj-web\public\projects\lake-house.png"
Copy-Item "$brain\project_commercial_1773604559241.png" "C:\Users\ozan_\L'art_Peyzaj\l-art-peyzaj-web\public\projects\commercial.png"
Write-Host "All images copied!"
